//------------------------------------------------------------------------------
// <autogenerated>
//     This Oxygene source code was generated by a tool.
//     Oxygene Version: 4.0.0.794
//     Runtime Version: 4.0.30319.1
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

{$HIDE CW3}
{$HIDE PW12}

namespace RemObjects.SDK.ApplePushProvider;

interface

uses
    System,
    RemObjects.SDK,
    RemObjects.SDK.Types,
    System.Collections.Generic;
    
type
    IApplePushProviderService = public interface(RemObjects.SDK.IROService)
    method registerDevice(deviceToken: RemObjects.SDK.Types.Binary; additionalInfo: System.String);
    method unregisterDevice(deviceToken: RemObjects.SDK.Types.Binary);
end;

ApplePushProviderService_Proxy = public partial class(RemObjects.SDK.Proxy, IApplePushProviderService)
protected 
    method __GetInterfaceName: System.String; override;
public 
    constructor(aMessage: RemObjects.SDK.IMessage; aClientChannel: RemObjects.SDK.IClientChannel);
    constructor(aMessage: RemObjects.SDK.IMessage; aClientChannel: RemObjects.SDK.IClientChannel; aOverrideInterfaceName: System.String);
    constructor(aRemoteService: RemObjects.SDK.IRemoteService);
    constructor(aRemoteService: RemObjects.SDK.IRemoteService; aOverrideInterfaceName: System.String);
    method registerDevice(deviceToken: RemObjects.SDK.Types.Binary; additionalInfo: System.String); virtual;
    method unregisterDevice(deviceToken: RemObjects.SDK.Types.Binary); virtual;
end;

CoApplePushProviderService = public class
public 
    class method &Create(aMessage: RemObjects.SDK.IMessage; aClientChannel: RemObjects.SDK.IClientChannel): IApplePushProviderService;
    class method &Create(aRemoteService: RemObjects.SDK.IRemoteService): IApplePushProviderService;
end;

IApplePushProviderService_Async = public interface(RemObjects.SDK.IROService_Async)
method BeginregisterDevice(deviceToken: RemObjects.SDK.Types.Binary; additionalInfo: System.String; __Callback: System.AsyncCallback; __UserData: System.Object): System.IAsyncResult;
method EndregisterDevice(__AsyncResult: System.IAsyncResult);
method BeginunregisterDevice(deviceToken: RemObjects.SDK.Types.Binary; __Callback: System.AsyncCallback; __UserData: System.Object): System.IAsyncResult;
method EndunregisterDevice(__AsyncResult: System.IAsyncResult);
end;

ApplePushProviderService_AsyncProxy = public partial class(RemObjects.SDK.AsyncProxy, IApplePushProviderService_Async)
protected 
    method __GetInterfaceName: System.String; override;
public 
    constructor(aMessage: RemObjects.SDK.IMessage; aClientChannel: RemObjects.SDK.IClientChannel);
    constructor(aMessage: RemObjects.SDK.IMessage; aClientChannel: RemObjects.SDK.IClientChannel; aOverrideInterfaceName: System.String);
    constructor(aRemoteService: RemObjects.SDK.IRemoteService);
    constructor(aRemoteService: RemObjects.SDK.IRemoteService; aOverrideInterfaceName: System.String);
    method BeginregisterDevice(deviceToken: RemObjects.SDK.Types.Binary; additionalInfo: System.String; __Callback: System.AsyncCallback; __UserData: System.Object): System.IAsyncResult; virtual;
    method EndregisterDevice(__AsyncResult: System.IAsyncResult); virtual;
    method BeginunregisterDevice(deviceToken: RemObjects.SDK.Types.Binary; __Callback: System.AsyncCallback; __UserData: System.Object): System.IAsyncResult; virtual;
    method EndunregisterDevice(__AsyncResult: System.IAsyncResult); virtual;
end;

implementation

{ ApplePushProviderService_Proxy }

method ApplePushProviderService_Proxy.__GetInterfaceName: System.String;
begin
    exit('ApplePushProviderService');
end;

constructor ApplePushProviderService_Proxy(aMessage: RemObjects.SDK.IMessage; aClientChannel: RemObjects.SDK.IClientChannel);
begin
    inherited constructor(aMessage, aClientChannel);
end;

constructor ApplePushProviderService_Proxy(aMessage: RemObjects.SDK.IMessage; aClientChannel: RemObjects.SDK.IClientChannel; aOverrideInterfaceName: System.String);
begin
    inherited constructor(aMessage, aClientChannel, aOverrideInterfaceName);
end;

constructor ApplePushProviderService_Proxy(aRemoteService: RemObjects.SDK.IRemoteService);
begin
    inherited constructor(aRemoteService);
end;

constructor ApplePushProviderService_Proxy(aRemoteService: RemObjects.SDK.IRemoteService; aOverrideInterfaceName: System.String);
begin
    inherited constructor(aRemoteService, aOverrideInterfaceName);
end;

method ApplePushProviderService_Proxy.registerDevice(deviceToken: RemObjects.SDK.Types.Binary; additionalInfo: System.String);
begin
    var __LocalMessage: RemObjects.SDK.IMessage := self.__GetMessage();
    __LocalMessage.InitializeRequestMessage(__ClientChannel, 'PushProvider', __GetActiveInterfaceName(), 'registerDevice');
    __LocalMessage.Write('deviceToken', deviceToken, typeOf(RemObjects.SDK.Types.Binary), RemObjects.SDK.StreamingFormat.Default);
    __LocalMessage.WriteUtf8String('additionalInfo', additionalInfo);
    __LocalMessage.FinalizeMessage();
    __ClientChannel.Dispatch(__LocalMessage);
    __LocalMessage.Clear();
end;

method ApplePushProviderService_Proxy.unregisterDevice(deviceToken: RemObjects.SDK.Types.Binary);
begin
    var __LocalMessage: RemObjects.SDK.IMessage := self.__GetMessage();
    __LocalMessage.InitializeRequestMessage(__ClientChannel, 'PushProvider', __GetActiveInterfaceName(), 'unregisterDevice');
    __LocalMessage.Write('deviceToken', deviceToken, typeOf(RemObjects.SDK.Types.Binary), RemObjects.SDK.StreamingFormat.Default);
    __LocalMessage.FinalizeMessage();
    __ClientChannel.Dispatch(__LocalMessage);
    __LocalMessage.Clear();
end;

{ CoApplePushProviderService }

class method CoApplePushProviderService.&Create(aMessage: RemObjects.SDK.IMessage; aClientChannel: RemObjects.SDK.IClientChannel): IApplePushProviderService;
begin
    exit(new ApplePushProviderService_Proxy(aMessage, aClientChannel));
end;

class method CoApplePushProviderService.&Create(aRemoteService: RemObjects.SDK.IRemoteService): IApplePushProviderService;
begin
    exit(new ApplePushProviderService_Proxy(aRemoteService));
end;

{ ApplePushProviderService_AsyncProxy }

method ApplePushProviderService_AsyncProxy.__GetInterfaceName: System.String;
begin
    exit('ApplePushProviderService');
end;

constructor ApplePushProviderService_AsyncProxy(aMessage: RemObjects.SDK.IMessage; aClientChannel: RemObjects.SDK.IClientChannel);
begin
    inherited constructor(aMessage, aClientChannel);
end;

constructor ApplePushProviderService_AsyncProxy(aMessage: RemObjects.SDK.IMessage; aClientChannel: RemObjects.SDK.IClientChannel; aOverrideInterfaceName: System.String);
begin
    inherited constructor(aMessage, aClientChannel, aOverrideInterfaceName);
end;

constructor ApplePushProviderService_AsyncProxy(aRemoteService: RemObjects.SDK.IRemoteService);
begin
    inherited constructor(aRemoteService);
end;

constructor ApplePushProviderService_AsyncProxy(aRemoteService: RemObjects.SDK.IRemoteService; aOverrideInterfaceName: System.String);
begin
    inherited constructor(aRemoteService, aOverrideInterfaceName);
end;

method ApplePushProviderService_AsyncProxy.BeginregisterDevice(deviceToken: RemObjects.SDK.Types.Binary; additionalInfo: System.String; __Callback: System.AsyncCallback; __UserData: System.Object): System.IAsyncResult;
begin
    var __LocalMessage: RemObjects.SDK.IMessage := self.__GetMessage();
    __LocalMessage.InitializeRequestMessage(__ClientChannel, 'PushProvider', __GetActiveInterfaceName(), 'registerDevice');
    __LocalMessage.Write('deviceToken', deviceToken, typeOf(RemObjects.SDK.Types.Binary), RemObjects.SDK.StreamingFormat.Default);
    __LocalMessage.WriteUtf8String('additionalInfo', additionalInfo);
    __LocalMessage.FinalizeMessage();
    exit(__ClientChannel.AsyncDispatch(__LocalMessage, __Callback, __UserData));
end;

method ApplePushProviderService_AsyncProxy.EndregisterDevice(__AsyncResult: System.IAsyncResult);
begin
    var __LocalMessage: RemObjects.SDK.IMessage := (__AsyncResult as RemObjects.SDK.IClientAsyncResult).Message;
    __LocalMessage.Clear();
end;

method ApplePushProviderService_AsyncProxy.BeginunregisterDevice(deviceToken: RemObjects.SDK.Types.Binary; __Callback: System.AsyncCallback; __UserData: System.Object): System.IAsyncResult;
begin
    var __LocalMessage: RemObjects.SDK.IMessage := self.__GetMessage();
    __LocalMessage.InitializeRequestMessage(__ClientChannel, 'PushProvider', __GetActiveInterfaceName(), 'unregisterDevice');
    __LocalMessage.Write('deviceToken', deviceToken, typeOf(RemObjects.SDK.Types.Binary), RemObjects.SDK.StreamingFormat.Default);
    __LocalMessage.FinalizeMessage();
    exit(__ClientChannel.AsyncDispatch(__LocalMessage, __Callback, __UserData));
end;

method ApplePushProviderService_AsyncProxy.EndunregisterDevice(__AsyncResult: System.IAsyncResult);
begin
    var __LocalMessage: RemObjects.SDK.IMessage := (__AsyncResult as RemObjects.SDK.IClientAsyncResult).Message;
    __LocalMessage.Clear();
end;

end.
