//------------------------------------------------------------------------------
// <autogenerated>
//     This Oxygene source code was generated by a tool.
//     Runtime Version: 4.0.30319.17929
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

{$HIDE H7}
{$HIDE W1}
{$HIDE W27}
{$HIDE H11}

namespace RemObjects.SDK.Push;

interface

uses
  System,
  RemObjects.SDK,
  RemObjects.SDK.Types,
  System.Collections.Generic;
  
type
  IApplePushProviderService = public interface(RemObjects.SDK.IROService)
    method registerDevice(deviceToken: RemObjects.SDK.Types.Binary; additionalInfo: System.String);
    method unregisterDevice(deviceToken: RemObjects.SDK.Types.Binary);
  end;
  
  ApplePushProviderService_Proxy = public partial class(RemObjects.SDK.Proxy, IApplePushProviderService)
  protected 
    [System.CLSCompliantAttribute(false)]
    method __GetInterfaceName: System.String; override;
  public 
    constructor(aMessage: RemObjects.SDK.IMessage; aClientChannel: RemObjects.SDK.IClientChannel);
    constructor(aMessage: RemObjects.SDK.IMessage; aClientChannel: RemObjects.SDK.IClientChannel; aOverrideInterfaceName: System.String);
    constructor(aRemoteService: RemObjects.SDK.IRemoteService);
    constructor(aRemoteService: RemObjects.SDK.IRemoteService; aOverrideInterfaceName: System.String);
    constructor(aUri: System.Uri);
    constructor(aUrl: System.String);
    method registerDevice(deviceToken: RemObjects.SDK.Types.Binary; additionalInfo: System.String); virtual;
    method unregisterDevice(deviceToken: RemObjects.SDK.Types.Binary); virtual;
  end;
  
  CoApplePushProviderService = public class
  public 
    class method &Create(aMessage: RemObjects.SDK.IMessage; aClientChannel: RemObjects.SDK.IClientChannel): IApplePushProviderService;
    class method &Create(aRemoteService: RemObjects.SDK.IRemoteService): IApplePushProviderService;
    class method &Create(aUri: System.Uri): IApplePushProviderService;
    class method &Create(aUrl: System.String): IApplePushProviderService;
  end;
  
  IGooglePushProviderService = public interface(RemObjects.SDK.IROService)
    method registerDevice(registrationId: System.String; additionalInfo: System.String);
    method unregisterDevice(registrationId: System.String);
  end;
  
  GooglePushProviderService_Proxy = public partial class(RemObjects.SDK.Proxy, IGooglePushProviderService)
  protected 
    [System.CLSCompliantAttribute(false)]
    method __GetInterfaceName: System.String; override;
  public 
    constructor(aMessage: RemObjects.SDK.IMessage; aClientChannel: RemObjects.SDK.IClientChannel);
    constructor(aMessage: RemObjects.SDK.IMessage; aClientChannel: RemObjects.SDK.IClientChannel; aOverrideInterfaceName: System.String);
    constructor(aRemoteService: RemObjects.SDK.IRemoteService);
    constructor(aRemoteService: RemObjects.SDK.IRemoteService; aOverrideInterfaceName: System.String);
    constructor(aUri: System.Uri);
    constructor(aUrl: System.String);
    method registerDevice(registrationId: System.String; additionalInfo: System.String); virtual;
    method unregisterDevice(registrationId: System.String); virtual;
  end;
  
  CoGooglePushProviderService = public class
  public 
    class method &Create(aMessage: RemObjects.SDK.IMessage; aClientChannel: RemObjects.SDK.IClientChannel): IGooglePushProviderService;
    class method &Create(aRemoteService: RemObjects.SDK.IRemoteService): IGooglePushProviderService;
    class method &Create(aUri: System.Uri): IGooglePushProviderService;
    class method &Create(aUrl: System.String): IGooglePushProviderService;
  end;
  
  IApplePushProviderService_Async = public interface(RemObjects.SDK.IROService_Async)
    method BeginregisterDevice(deviceToken: RemObjects.SDK.Types.Binary; additionalInfo: System.String; __Callback: System.AsyncCallback; __UserData: System.Object): System.IAsyncResult;
    method EndregisterDevice(__AsyncResult: System.IAsyncResult);
    method BeginunregisterDevice(deviceToken: RemObjects.SDK.Types.Binary; __Callback: System.AsyncCallback; __UserData: System.Object): System.IAsyncResult;
    method EndunregisterDevice(__AsyncResult: System.IAsyncResult);
  end;
  
  ApplePushProviderService_AsyncProxy = public partial class(RemObjects.SDK.AsyncProxy, IApplePushProviderService_Async)
  protected 
    method __GetInterfaceName: System.String; override;
  public 
    constructor(aMessage: RemObjects.SDK.IMessage; aClientChannel: RemObjects.SDK.IClientChannel);
    constructor(aMessage: RemObjects.SDK.IMessage; aClientChannel: RemObjects.SDK.IClientChannel; aOverrideInterfaceName: System.String);
    constructor(aRemoteService: RemObjects.SDK.IRemoteService);
    constructor(aRemoteService: RemObjects.SDK.IRemoteService; aOverrideInterfaceName: System.String);
    constructor(aUri: System.Uri);
    constructor(aUrl: System.String);
    method BeginregisterDevice(deviceToken: RemObjects.SDK.Types.Binary; additionalInfo: System.String; __Callback: System.AsyncCallback; __UserData: System.Object): System.IAsyncResult; virtual;
    method EndregisterDevice(__AsyncResult: System.IAsyncResult); virtual;
    method BeginunregisterDevice(deviceToken: RemObjects.SDK.Types.Binary; __Callback: System.AsyncCallback; __UserData: System.Object): System.IAsyncResult; virtual;
    method EndunregisterDevice(__AsyncResult: System.IAsyncResult); virtual;
  end;
  
  IGooglePushProviderService_Async = public interface(RemObjects.SDK.IROService_Async)
    method BeginregisterDevice(registrationId: System.String; additionalInfo: System.String; __Callback: System.AsyncCallback; __UserData: System.Object): System.IAsyncResult;
    method EndregisterDevice(__AsyncResult: System.IAsyncResult);
    method BeginunregisterDevice(registrationId: System.String; __Callback: System.AsyncCallback; __UserData: System.Object): System.IAsyncResult;
    method EndunregisterDevice(__AsyncResult: System.IAsyncResult);
  end;
  
  GooglePushProviderService_AsyncProxy = public partial class(RemObjects.SDK.AsyncProxy, IGooglePushProviderService_Async)
  protected 
    method __GetInterfaceName: System.String; override;
  public 
    constructor(aMessage: RemObjects.SDK.IMessage; aClientChannel: RemObjects.SDK.IClientChannel);
    constructor(aMessage: RemObjects.SDK.IMessage; aClientChannel: RemObjects.SDK.IClientChannel; aOverrideInterfaceName: System.String);
    constructor(aRemoteService: RemObjects.SDK.IRemoteService);
    constructor(aRemoteService: RemObjects.SDK.IRemoteService; aOverrideInterfaceName: System.String);
    constructor(aUri: System.Uri);
    constructor(aUrl: System.String);
    method BeginregisterDevice(registrationId: System.String; additionalInfo: System.String; __Callback: System.AsyncCallback; __UserData: System.Object): System.IAsyncResult; virtual;
    method EndregisterDevice(__AsyncResult: System.IAsyncResult); virtual;
    method BeginunregisterDevice(registrationId: System.String; __Callback: System.AsyncCallback; __UserData: System.Object): System.IAsyncResult; virtual;
    method EndunregisterDevice(__AsyncResult: System.IAsyncResult); virtual;
  end;
  
implementation

{ ApplePushProviderService_Proxy }

method ApplePushProviderService_Proxy.__GetInterfaceName: System.String;
begin
  exit('ApplePushProviderService');
end;

constructor ApplePushProviderService_Proxy(aMessage: RemObjects.SDK.IMessage; aClientChannel: RemObjects.SDK.IClientChannel);
begin
  inherited constructor(aMessage, aClientChannel);
end;

constructor ApplePushProviderService_Proxy(aMessage: RemObjects.SDK.IMessage; aClientChannel: RemObjects.SDK.IClientChannel; aOverrideInterfaceName: System.String);
begin
  inherited constructor(aMessage, aClientChannel, aOverrideInterfaceName);
end;

constructor ApplePushProviderService_Proxy(aRemoteService: RemObjects.SDK.IRemoteService);
begin
  inherited constructor(aRemoteService);
end;

constructor ApplePushProviderService_Proxy(aRemoteService: RemObjects.SDK.IRemoteService; aOverrideInterfaceName: System.String);
begin
  inherited constructor(aRemoteService, aOverrideInterfaceName);
end;

constructor ApplePushProviderService_Proxy(aUri: System.Uri);
begin
  inherited constructor(aUri);
end;

constructor ApplePushProviderService_Proxy(aUrl: System.String);
begin
  inherited constructor(aUrl);
end;

method ApplePushProviderService_Proxy.registerDevice(deviceToken: RemObjects.SDK.Types.Binary; additionalInfo: System.String);
begin
  var __LocalMessage: RemObjects.SDK.IMessage := self.__GetMessage();
  __LocalMessage.InitializeRequestMessage(__ClientChannel, 'PushProvider', __GetActiveInterfaceName(), 'registerDevice');
  __LocalMessage.Write('deviceToken', deviceToken, typeOf(RemObjects.SDK.Types.Binary), RemObjects.SDK.StreamingFormat.Default);
  __LocalMessage.WriteUtf8String('additionalInfo', additionalInfo);
  __LocalMessage.FinalizeMessage();
  __ClientChannel.Dispatch(__LocalMessage);
  __LocalMessage.Clear();
end;

method ApplePushProviderService_Proxy.unregisterDevice(deviceToken: RemObjects.SDK.Types.Binary);
begin
  var __LocalMessage: RemObjects.SDK.IMessage := self.__GetMessage();
  __LocalMessage.InitializeRequestMessage(__ClientChannel, 'PushProvider', __GetActiveInterfaceName(), 'unregisterDevice');
  __LocalMessage.Write('deviceToken', deviceToken, typeOf(RemObjects.SDK.Types.Binary), RemObjects.SDK.StreamingFormat.Default);
  __LocalMessage.FinalizeMessage();
  __ClientChannel.Dispatch(__LocalMessage);
  __LocalMessage.Clear();
end;

{ CoApplePushProviderService }

class method CoApplePushProviderService.&Create(aMessage: RemObjects.SDK.IMessage; aClientChannel: RemObjects.SDK.IClientChannel): IApplePushProviderService;
begin
  exit(new ApplePushProviderService_Proxy(aMessage, aClientChannel));
end;

class method CoApplePushProviderService.&Create(aRemoteService: RemObjects.SDK.IRemoteService): IApplePushProviderService;
begin
  exit(new ApplePushProviderService_Proxy(aRemoteService));
end;

class method CoApplePushProviderService.&Create(aUri: System.Uri): IApplePushProviderService;
begin
  exit(new ApplePushProviderService_Proxy(aUri));
end;

class method CoApplePushProviderService.&Create(aUrl: System.String): IApplePushProviderService;
begin
  exit(new ApplePushProviderService_Proxy(aUrl));
end;

{ GooglePushProviderService_Proxy }

method GooglePushProviderService_Proxy.__GetInterfaceName: System.String;
begin
  exit('GooglePushProviderService');
end;

constructor GooglePushProviderService_Proxy(aMessage: RemObjects.SDK.IMessage; aClientChannel: RemObjects.SDK.IClientChannel);
begin
  inherited constructor(aMessage, aClientChannel);
end;

constructor GooglePushProviderService_Proxy(aMessage: RemObjects.SDK.IMessage; aClientChannel: RemObjects.SDK.IClientChannel; aOverrideInterfaceName: System.String);
begin
  inherited constructor(aMessage, aClientChannel, aOverrideInterfaceName);
end;

constructor GooglePushProviderService_Proxy(aRemoteService: RemObjects.SDK.IRemoteService);
begin
  inherited constructor(aRemoteService);
end;

constructor GooglePushProviderService_Proxy(aRemoteService: RemObjects.SDK.IRemoteService; aOverrideInterfaceName: System.String);
begin
  inherited constructor(aRemoteService, aOverrideInterfaceName);
end;

constructor GooglePushProviderService_Proxy(aUri: System.Uri);
begin
  inherited constructor(aUri);
end;

constructor GooglePushProviderService_Proxy(aUrl: System.String);
begin
  inherited constructor(aUrl);
end;

method GooglePushProviderService_Proxy.registerDevice(registrationId: System.String; additionalInfo: System.String);
begin
  var __LocalMessage: RemObjects.SDK.IMessage := self.__GetMessage();
  __LocalMessage.InitializeRequestMessage(__ClientChannel, 'PushProvider', __GetActiveInterfaceName(), 'registerDevice');
  __LocalMessage.WriteAnsiString('registrationId', registrationId);
  __LocalMessage.WriteAnsiString('additionalInfo', additionalInfo);
  __LocalMessage.FinalizeMessage();
  __ClientChannel.Dispatch(__LocalMessage);
  __LocalMessage.Clear();
end;

method GooglePushProviderService_Proxy.unregisterDevice(registrationId: System.String);
begin
  var __LocalMessage: RemObjects.SDK.IMessage := self.__GetMessage();
  __LocalMessage.InitializeRequestMessage(__ClientChannel, 'PushProvider', __GetActiveInterfaceName(), 'unregisterDevice');
  __LocalMessage.WriteAnsiString('registrationId', registrationId);
  __LocalMessage.FinalizeMessage();
  __ClientChannel.Dispatch(__LocalMessage);
  __LocalMessage.Clear();
end;

{ CoGooglePushProviderService }

class method CoGooglePushProviderService.&Create(aMessage: RemObjects.SDK.IMessage; aClientChannel: RemObjects.SDK.IClientChannel): IGooglePushProviderService;
begin
  exit(new GooglePushProviderService_Proxy(aMessage, aClientChannel));
end;

class method CoGooglePushProviderService.&Create(aRemoteService: RemObjects.SDK.IRemoteService): IGooglePushProviderService;
begin
  exit(new GooglePushProviderService_Proxy(aRemoteService));
end;

class method CoGooglePushProviderService.&Create(aUri: System.Uri): IGooglePushProviderService;
begin
  exit(new GooglePushProviderService_Proxy(aUri));
end;

class method CoGooglePushProviderService.&Create(aUrl: System.String): IGooglePushProviderService;
begin
  exit(new GooglePushProviderService_Proxy(aUrl));
end;

{ ApplePushProviderService_AsyncProxy }

method ApplePushProviderService_AsyncProxy.__GetInterfaceName: System.String;
begin
  exit('ApplePushProviderService');
end;

constructor ApplePushProviderService_AsyncProxy(aMessage: RemObjects.SDK.IMessage; aClientChannel: RemObjects.SDK.IClientChannel);
begin
  inherited constructor(aMessage, aClientChannel);
end;

constructor ApplePushProviderService_AsyncProxy(aMessage: RemObjects.SDK.IMessage; aClientChannel: RemObjects.SDK.IClientChannel; aOverrideInterfaceName: System.String);
begin
  inherited constructor(aMessage, aClientChannel, aOverrideInterfaceName);
end;

constructor ApplePushProviderService_AsyncProxy(aRemoteService: RemObjects.SDK.IRemoteService);
begin
  inherited constructor(aRemoteService);
end;

constructor ApplePushProviderService_AsyncProxy(aRemoteService: RemObjects.SDK.IRemoteService; aOverrideInterfaceName: System.String);
begin
  inherited constructor(aRemoteService, aOverrideInterfaceName);
end;

constructor ApplePushProviderService_AsyncProxy(aUri: System.Uri);
begin
  inherited constructor(aUri);
end;

constructor ApplePushProviderService_AsyncProxy(aUrl: System.String);
begin
  inherited constructor(aUrl);
end;

method ApplePushProviderService_AsyncProxy.BeginregisterDevice(deviceToken: RemObjects.SDK.Types.Binary; additionalInfo: System.String; __Callback: System.AsyncCallback; __UserData: System.Object): System.IAsyncResult;
begin
  var __LocalMessage: RemObjects.SDK.IMessage := self.__GetMessage();
  __LocalMessage.InitializeRequestMessage(__ClientChannel, 'PushProvider', __GetActiveInterfaceName(), 'registerDevice');
  __LocalMessage.Write('deviceToken', deviceToken, typeOf(RemObjects.SDK.Types.Binary), RemObjects.SDK.StreamingFormat.Default);
  __LocalMessage.WriteUtf8String('additionalInfo', additionalInfo);
  __LocalMessage.FinalizeMessage();
  exit(__ClientChannel.AsyncDispatch(__LocalMessage, __Callback, __UserData));
end;

method ApplePushProviderService_AsyncProxy.EndregisterDevice(__AsyncResult: System.IAsyncResult);
begin
  var __LocalMessage: RemObjects.SDK.IMessage := (__AsyncResult as RemObjects.SDK.IClientAsyncResult).Message;
  __LocalMessage.Clear();
end;

method ApplePushProviderService_AsyncProxy.BeginunregisterDevice(deviceToken: RemObjects.SDK.Types.Binary; __Callback: System.AsyncCallback; __UserData: System.Object): System.IAsyncResult;
begin
  var __LocalMessage: RemObjects.SDK.IMessage := self.__GetMessage();
  __LocalMessage.InitializeRequestMessage(__ClientChannel, 'PushProvider', __GetActiveInterfaceName(), 'unregisterDevice');
  __LocalMessage.Write('deviceToken', deviceToken, typeOf(RemObjects.SDK.Types.Binary), RemObjects.SDK.StreamingFormat.Default);
  __LocalMessage.FinalizeMessage();
  exit(__ClientChannel.AsyncDispatch(__LocalMessage, __Callback, __UserData));
end;

method ApplePushProviderService_AsyncProxy.EndunregisterDevice(__AsyncResult: System.IAsyncResult);
begin
  var __LocalMessage: RemObjects.SDK.IMessage := (__AsyncResult as RemObjects.SDK.IClientAsyncResult).Message;
  __LocalMessage.Clear();
end;

{ GooglePushProviderService_AsyncProxy }

method GooglePushProviderService_AsyncProxy.__GetInterfaceName: System.String;
begin
  exit('GooglePushProviderService');
end;

constructor GooglePushProviderService_AsyncProxy(aMessage: RemObjects.SDK.IMessage; aClientChannel: RemObjects.SDK.IClientChannel);
begin
  inherited constructor(aMessage, aClientChannel);
end;

constructor GooglePushProviderService_AsyncProxy(aMessage: RemObjects.SDK.IMessage; aClientChannel: RemObjects.SDK.IClientChannel; aOverrideInterfaceName: System.String);
begin
  inherited constructor(aMessage, aClientChannel, aOverrideInterfaceName);
end;

constructor GooglePushProviderService_AsyncProxy(aRemoteService: RemObjects.SDK.IRemoteService);
begin
  inherited constructor(aRemoteService);
end;

constructor GooglePushProviderService_AsyncProxy(aRemoteService: RemObjects.SDK.IRemoteService; aOverrideInterfaceName: System.String);
begin
  inherited constructor(aRemoteService, aOverrideInterfaceName);
end;

constructor GooglePushProviderService_AsyncProxy(aUri: System.Uri);
begin
  inherited constructor(aUri);
end;

constructor GooglePushProviderService_AsyncProxy(aUrl: System.String);
begin
  inherited constructor(aUrl);
end;

method GooglePushProviderService_AsyncProxy.BeginregisterDevice(registrationId: System.String; additionalInfo: System.String; __Callback: System.AsyncCallback; __UserData: System.Object): System.IAsyncResult;
begin
  var __LocalMessage: RemObjects.SDK.IMessage := self.__GetMessage();
  __LocalMessage.InitializeRequestMessage(__ClientChannel, 'PushProvider', __GetActiveInterfaceName(), 'registerDevice');
  __LocalMessage.WriteAnsiString('registrationId', registrationId);
  __LocalMessage.WriteAnsiString('additionalInfo', additionalInfo);
  __LocalMessage.FinalizeMessage();
  exit(__ClientChannel.AsyncDispatch(__LocalMessage, __Callback, __UserData));
end;

method GooglePushProviderService_AsyncProxy.EndregisterDevice(__AsyncResult: System.IAsyncResult);
begin
  var __LocalMessage: RemObjects.SDK.IMessage := (__AsyncResult as RemObjects.SDK.IClientAsyncResult).Message;
  __LocalMessage.Clear();
end;

method GooglePushProviderService_AsyncProxy.BeginunregisterDevice(registrationId: System.String; __Callback: System.AsyncCallback; __UserData: System.Object): System.IAsyncResult;
begin
  var __LocalMessage: RemObjects.SDK.IMessage := self.__GetMessage();
  __LocalMessage.InitializeRequestMessage(__ClientChannel, 'PushProvider', __GetActiveInterfaceName(), 'unregisterDevice');
  __LocalMessage.WriteAnsiString('registrationId', registrationId);
  __LocalMessage.FinalizeMessage();
  exit(__ClientChannel.AsyncDispatch(__LocalMessage, __Callback, __UserData));
end;

method GooglePushProviderService_AsyncProxy.EndunregisterDevice(__AsyncResult: System.IAsyncResult);
begin
  var __LocalMessage: RemObjects.SDK.IMessage := (__AsyncResult as RemObjects.SDK.IClientAsyncResult).Message;
  __LocalMessage.Clear();
end;

end.
