//----------------------------------------------------------------------
// This file was automatically generated by the RemObjects SDK from a
// RODL file associated with this project.
//
// Do not modify this file manually, or your changes will be lost when
// it is regenerated the next time you update your RODL.
//----------------------------------------------------------------------

package com.remobjects.push.sample.intf;


public interface Defines {

	String TARGET_NAMESPACE = "com.remobjects.push.sample.intf";
	String IGooglePushProviderService_IID = "{33BC7B12-E712-4052-A5DE-FFF96DAEE687}";

}
