//----------------------------------------------------------------------
// This file was automatically generated by the RemObjects SDK from a
// RODL file associated with this project.
//
// Do not modify this file manually, or your changes will be lost when
// it is regenerated the next time you update your RODL.
//----------------------------------------------------------------------

package com.remobjects.push.sample.intf;

import com.remobjects.sdk.*;

public class ROEventsAdapter implements IROEvents {

	@Override
	public void OnException(OnExceptionEvent aEvent) {}

}
