//------------------------------------------------------------------------------
// <autogenerated>
//     This Oxygene source code was generated by a tool.
//     Runtime Version: 4.0.30319.17929
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

{$HIDE H7}
{$HIDE W1}
{$HIDE W27}
{$HIDE H11}

namespace RemObjects.SDK.Push;

interface

uses
  System,
  RemObjects.SDK,
  RemObjects.SDK.Types,
  System.Collections.Generic;
  
type
  IApplePushProviderService = public interface(RemObjects.SDK.IROService)
    method registerDevice(deviceToken: RemObjects.SDK.Types.Binary; additionalInfo: System.String);
    method unregisterDevice(deviceToken: RemObjects.SDK.Types.Binary);
  end;
  
 
  IGooglePushProviderService = public interface(RemObjects.SDK.IROService)
    method registerDevice(registrationId: System.String; additionalInfo: System.String);
    method unregisterDevice(registrationId: System.String);
  end;

  
  IApplePushProviderService_Async = public interface(RemObjects.SDK.IROService_Async)
    method BeginregisterDevice(deviceToken: RemObjects.SDK.Types.Binary; additionalInfo: System.String; __Callback: System.AsyncCallback; __UserData: System.Object): System.IAsyncResult;
    method EndregisterDevice(__AsyncResult: System.IAsyncResult);
    method BeginunregisterDevice(deviceToken: RemObjects.SDK.Types.Binary; __Callback: System.AsyncCallback; __UserData: System.Object): System.IAsyncResult;
    method EndunregisterDevice(__AsyncResult: System.IAsyncResult);
  end;
  
  
  
  IGooglePushProviderService_Async = public interface(RemObjects.SDK.IROService_Async)
    method BeginregisterDevice(registrationId: System.String; additionalInfo: System.String; __Callback: System.AsyncCallback; __UserData: System.Object): System.IAsyncResult;
    method EndregisterDevice(__AsyncResult: System.IAsyncResult);
    method BeginunregisterDevice(registrationId: System.String; __Callback: System.AsyncCallback; __UserData: System.Object): System.IAsyncResult;
    method EndunregisterDevice(__AsyncResult: System.IAsyncResult);
  end;
  
  
  
implementation


end.
